// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";

/// @notice Asserts Solidity encoding matches the Rust circuit for every leaf, root, digest,
///         and the batch commitment. Vectors are generated by `zk/script` bin `fixture --parity`.
contract ZkAttributionParityTest is Test {
    using stdJson for string;

    string internal vectors;

    function setUp() public {
        vectors = vm.readFile("./test/fixtures/zk-attribution-vectors.json");
    }

    function test_attributionTypehash() public view {
        bytes32 expected = vectors.readBytes32(".attributionTypehash");
        bytes32 actual =
            keccak256("Attribution(bytes32 channelId,address payTo,uint128 cumulativeAmount)");
        assertEq(actual, expected);
    }

    function test_emptyRoot() public view {
        assertEq(vectors.readBytes32(".emptyRoot"), bytes32(0));
    }

    function test_pairLeavesAndRoot() public view {
        uint256 n = vectors.readUint(".pairCount");
        bytes32[] memory leaves = new bytes32[](n);
        for (uint256 i = 0; i < n; ++i) {
            address payTo = vectors.readAddress(string.concat(".pairs[", vm.toString(i), "].payTo"));
            uint128 cumulative =
                uint128(vectors.readUint(string.concat(".pairs[", vm.toString(i), "].cumulative")));
            bytes32 leaf = keccak256(abi.encode(payTo, cumulative));
            assertEq(leaf, vectors.readBytes32(string.concat(".pairs[", vm.toString(i), "].leaf")));
            leaves[i] = leaf;
        }
        bytes32 root = n == 0 ? bytes32(0) : keccak256(abi.encodePacked(leaves));
        assertEq(root, vectors.readBytes32(".root"));
    }

    function test_attributionDigest() public view {
        bytes32 domain = vectors.readBytes32(".attributionDigest.domainSeparator");
        bytes32 channelId = vectors.readBytes32(".attributionDigest.channelId");
        address payTo = vectors.readAddress(".attributionDigest.payTo");
        uint128 cumulative = uint128(vectors.readUint(".attributionDigest.cumulative"));

        bytes32 typehash =
            keccak256("Attribution(bytes32 channelId,address payTo,uint128 cumulativeAmount)");
        bytes32 structHash = keccak256(abi.encode(typehash, channelId, payTo, cumulative));
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domain, structHash));
        assertEq(digest, vectors.readBytes32(".attributionDigest.digest"));
    }

    function test_claimLeaf() public view {
        bytes32 leaf = keccak256(
            abi.encode(
                vectors.readBytes32(".claimLeaf.channelId"),
                vectors.readAddress(".claimLeaf.payer"),
                vectors.readAddress(".claimLeaf.payerAuthorizer"),
                vectors.readAddress(".claimLeaf.token"),
                uint128(vectors.readUint(".claimLeaf.priorClaimed")),
                uint128(vectors.readUint(".claimLeaf.totalClaimed")),
                vectors.readBytes32(".claimLeaf.oldRoot"),
                vectors.readBytes32(".claimLeaf.newRoot")
            )
        );
        assertEq(leaf, vectors.readBytes32(".claimLeaf.leaf"));
    }

    function test_creditLeaf() public view {
        bytes32 leaf = keccak256(
            abi.encode(
                vectors.readAddress(".creditLeaf.receiver"),
                vectors.readAddress(".creditLeaf.token"),
                uint128(vectors.readUint(".creditLeaf.amount"))
            )
        );
        assertEq(leaf, vectors.readBytes32(".creditLeaf.leaf"));
    }

    function test_batchCommitment() public view {
        bytes32 domain = vectors.readBytes32(".batch.domainSeparator");
        uint256 n = vectors.readUint(".batch.claimLeafCount");
        uint256 m = vectors.readUint(".batch.creditLeafCount");
        bytes32[] memory claimLeaves = new bytes32[](n);
        for (uint256 i = 0; i < n; ++i) {
            claimLeaves[i] = vectors.readBytes32(string.concat(".batch.claimLeaves[", vm.toString(i), "]"));
        }
        bytes32[] memory creditLeaves = new bytes32[](m);
        for (uint256 j = 0; j < m; ++j) {
            creditLeaves[j] =
                vectors.readBytes32(string.concat(".batch.creditLeaves[", vm.toString(j), "]"));
        }
        bytes32 commitment = keccak256(
            abi.encode(domain, keccak256(abi.encodePacked(claimLeaves)), keccak256(abi.encodePacked(creditLeaves)))
        );
        assertEq(commitment, vectors.readBytes32(".batch.batchCommitment"));
        assertEq(commitment, vectors.readBytes32(".batch.witnessCommitment"));
    }
}

